site_name: Aniol Martí Docs
site_description: Some useful documentation.
site_author: Aniol Martí
site_url: https://docs.aniolmarti.cat
repo_url: https://github.com/aniolm9/docs.aniolmarti.cat
copyright: Copyright &copy; 2022 <a href="https://twitter.com/aniol_marti">Aniol Martí</a>.
docs_dir: docs/
